<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ParametroDetalle;

class ParametroDetalleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $parametro_detalles = array(
            array(
                "id" => 1,
                "nombre" => "UNIDAD",
                "parametro_id" => 1,
                "value" => 1,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 4,
                "nombre" => "KILOGRAMO",
                "parametro_id" => 1,
                "value" => 2,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 5,
                "nombre" => "METRO",
                "parametro_id" => 1,
                "value" => 3,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 6,
                "nombre" => "METRO CUADRADO",
                "parametro_id" => 1,
                "value" => 4,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 7,
                "nombre" => "METRO CÚBICO",
                "parametro_id" => 1,
                "value" => 5,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 8,
                "nombre" => "AMAZONAS",
                "parametro_id" => 2,
                "value" => 1,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 9,
                "nombre" => "ANTIOQUIA",
                "parametro_id" => 2,
                "value" => 2,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 10,
                "nombre" => "ARAUCA",
                "parametro_id" => 2,
                "value" => 3,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 11,
                "nombre" => "ATLÁNTICO",
                "parametro_id" => 2,
                "value" => 4,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 12,
                "nombre" => "BOGOTÁ",
                "parametro_id" => 2,
                "value" => 5,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 13,
                "nombre" => "BOLÍVAR",
                "parametro_id" => 2,
                "value" => 6,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 14,
                "nombre" => "BOYACÁ",
                "parametro_id" => 2,
                "value" => 7,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 15,
                "nombre" => "CALDAS",
                "parametro_id" => 2,
                "value" => 8,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 16,
                "nombre" => "CAQUETÁ",
                "parametro_id" => 2,
                "value" => 9,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 17,
                "nombre" => "CASANARE",
                "parametro_id" => 2,
                "value" => 10,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 18,
                "nombre" => "CAUCA",
                "parametro_id" => 2,
                "value" => 11,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 19,
                "nombre" => "CESAR",
                "parametro_id" => 2,
                "value" => 12,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 20,
                "nombre" => "CHOCÓ",
                "parametro_id" => 2,
                "value" => 13,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 21,
                "nombre" => "CÓRDOBA",
                "parametro_id" => 2,
                "value" => 14,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 22,
                "nombre" => "CUNDINAMARCA",
                "parametro_id" => 2,
                "value" => 15,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 23,
                "nombre" => "GUAINÍA",
                "parametro_id" => 2,
                "value" => 16,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 24,
                "nombre" => "GUAVIARE",
                "parametro_id" => 2,
                "value" => 17,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 25,
                "nombre" => "HUILA",
                "parametro_id" => 2,
                "value" => 18,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 26,
                "nombre" => "LA GUAJIRA",
                "parametro_id" => 2,
                "value" => 19,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 27,
                "nombre" => "MAGDALENA",
                "parametro_id" => 2,
                "value" => 20,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 28,
                "nombre" => "META",
                "parametro_id" => 2,
                "value" => 21,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 29,
                "nombre" => "NARIÑO",
                "parametro_id" => 2,
                "value" => 22,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 30,
                "nombre" => "NORTE DE SANTANDER",
                "parametro_id" => 2,
                "value" => 23,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 31,
                "nombre" => "PUTUMAYO",
                "parametro_id" => 2,
                "value" => 24,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 32,
                "nombre" => "QUINDÍO",
                "parametro_id" => 2,
                "value" => 25,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 33,
                "nombre" => "RISARALDA",
                "parametro_id" => 2,
                "value" => 26,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 34,
                "nombre" => "SAN ANDRÉS Y PROVIDENCIA",
                "parametro_id" => 2,
                "value" => 27,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 35,
                "nombre" => "SANTANDER",
                "parametro_id" => 2,
                "value" => 28,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 36,
                "nombre" => "SUCRE",
                "parametro_id" => 2,
                "value" => 29,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 37,
                "nombre" => "TOLIMA",
                "parametro_id" => 2,
                "value" => 30,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 38,
                "nombre" => "VALLE DEL CAUCA",
                "parametro_id" => 2,
                "value" => 31,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 39,
                "nombre" => "VAUPÉS",
                "parametro_id" => 2,
                "value" => 32,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
            array(
                "id" => 40,
                "nombre" => "VICHADA",
                "parametro_id" => 2,
                "value" => 33,
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s"),
            ),
        );
        $parametrosDetalle = new ParametroDetalle();
        $parametrosDetalle->insert($parametro_detalles);        
    }
}
